apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-java-image
spec:
  params:
    - name: IMAGE
      type: string
      description: The image to build.
    - name: SOURCE_URL
      type: string
      description: The git repo url.
    - name: SOURCE_REVISION
      type: string
      description: The git revision.
    - name: BUILDER_IMAGE
      type: string
      description: The builder image to be used.
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.SOURCE_URL)
        - name: revision
          value: $(params.SOURCE_REVISION)
      workspaces:
        - name: output
          workspace: source-workspace
    - name: build-image
      taskRef:
        name: buildpacks
      params:
        - name: APP_IMAGE
          value: $(params.IMAGE)
        - name: BUILDER_IMAGE
          value: $(params.BUILDER_IMAGE)
      workspaces:
        - name: source
          workspace: source-workspace
        - name: dockerconfig
          workspace: docker-config
      runAfter:
        - fetch-source
  workspaces:
    - name: source-workspace
    - name: docker-config