apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildpacks-build-java
spec:
  params:
    - name: IMAGE
      type: string
      description: The image to build.
    - name: BUILDER_IMAGE
      type: string
      description: The builder image to use.
      default: paketobuildpacks/builder:base
  steps:
    - name: build
      image: gcr.io/tekton-releases/github.com/tektoncd/catalog/task/buildpacks/0.2/buildpacks
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: BUILDER_IMAGE
          value: $(params.BUILDER_IMAGE)
      workingDir: /workspace/source
      volumeMounts:
        - name: source-repo
          mountPath: /workspace/source
  volumes:
    - name: source-repo
      emptyDir: {}
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-java-image
spec:
  params:
    - name: IMAGE
      type: string
      description: The image to build.
    - name: SOURCE_URL
      type: string
      description: The git repo url.
    - name: SOURCE_REVISION
      type: string
      description: The git revision.
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.SOURCE_URL)
        - name: revision
          value: $(params.SOURCE_REVISION)
      workspaces:
        - name: output
          workspace: source-workspace
    - name: build-image
      taskRef:
        name: buildpacks-build-java
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      workspaces:
        - name: source-repo
          workspace: source-workspace
      runAfter:
        - fetch-source
  workspaces:
    - name: source-workspace