apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-java-image-run
spec:
  pipelineRef:
    name: build-java-image
  params:
    - name: IMAGE
      value: localhost:5000/buildpacktest
    - name: BUILDER_IMAGE
      value: paketobuildpacks/builder:base
    - name: SOURCE_URL
      value: https://github.com/sudhishmk/tektonbuildpack.git
    - name: SOURCE_REVISION
      value: main
  workspaces:
    - name: source-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-config
      secret:
        secretName: docker-config